[package]
name = "advent-of-code-rust"
version = "0.1.0"
authors = ["Randall Mason <randall@mason.ch>"]

[lib]
bench = false

[dependencies]
aoc-runner = "0.3.0"
aoc-runner-derive = "0.3.0"
regex = "1"
lazy_static = "1"
